name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ github.repository }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: cd 01-firsprg/asm && make